# Generated by Django 5.0.1 on 2025-12-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experience/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
