# Generated by Django 5.0.1 on 2025-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_image_experience_image_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('graphic_design', 'Graphic Design'), ('ms_office', 'Microsoft Office'), ('tools', 'Tools'), ('soft', 'Soft Skills')], max_length=50),
        ),
    ]
